version: "3.5"

services:
  mongo:
    container_name: mongo_dev
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - dev

## only used for initial seeding
## use mongorestore from mongodump afterwards

#  mongo_seed:
#    container_name: mongo_seed
#    build:
#      dockerfile: Dockerfile
#      context: ./mongo_seed
#    networks:
#      - dev
#    depends_on:
#      - mongo

  mongo_restore:
    container_name: mongo_restore
    build:
      dockerfile: Dockerfile
      context: ./mongo_restore
    networks:
      - dev
    depends_on:
      - mongo  




networks:
  dev:
    driver: bridge
